"""
Django settings for food_sort_system project.

Generated by 'django-admin startproject' using Django 4.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^0+j2%jr91kwx8sdviw1p++&@^ble7#r*-bhip^9*u!hpbmjv0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ========== 核心修复1：允许后端外网访问 ==========
ALLOWED_HOSTS = [
    "3f7748e1.r10.cpolar.top",  # 后端内网穿透域名
    "localhost",
    "127.0.0.1",
    "0.0.0.0",
]


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 已有的应用
    'category.apps.CategoryConfig',
    'corsheaders',  # 跨域应用
    
    # 新增：注册 DRF
    'rest_framework',
]

MIDDLEWARE = [
    # 新增：跨域中间件（必须放在首位）
    'corsheaders.middleware.CorsMiddleware',
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # 保留CSRF中间件（不注释）
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'food_sort_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'food_sort_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'zh-hans'  # 中文
TIME_ZONE = 'Asia/Shanghai'  # 上海时区
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ========== 核心修复2：跨域配置（适配HTTPS/HTTP） ==========
# 允许携带Cookie（CSRF Token核心）
CORS_ALLOW_CREDENTIALS = True

# 允许的跨域源（精准匹配前端域名，包含端口）
CORS_ALLOWED_ORIGINS = [
    "http://16d0a48d.r10.cpolar.top:5174",  # 前端HTTP域名
    "https://16d0a48d.r10.cpolar.top:5174", # 前端HTTPS域名（新增）
    "http://localhost:5174",
    "http://127.0.0.1:5174",
]

# 允许的请求头（包含HTTPS环境的CSRF Token头）
CORS_ALLOW_HEADERS = [
    "X-CSRFToken",
    "Content-Type",
    "Authorization",
    "Origin",
    "Referer",
    "X-Requested-With",
]

# 允许的请求方法
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "OPTIONS",
]

# ========== 核心修复3：CSRF配置（解决HTTPS 403） ==========
# 1. CSRF信任的源（包含HTTPS/HTTP的前端/后端域名）
CSRF_TRUSTED_ORIGINS = [
    "http://16d0a48d.r10.cpolar.top:5174",   # 前端HTTP
    "https://16d0a48d.r10.cpolar.top:5174",  # 前端HTTPS（新增）
    "http://3f7748e1.r10.cpolar.top",        # 后端HTTP
    "https://3f7748e1.r10.cpolar.top",       # 后端HTTPS（新增）
    "http://localhost:5174",
]

# 2. 关闭HTTPS强制Cookie（关键！适配内网穿透的HTTP环境）
CSRF_COOKIE_SECURE = False  # HTTPS环境设为True，HTTP设为False
SESSION_COOKIE_SECURE = False  # 同步关闭Session的HTTPS强制

# 3. 关闭SameSite严格模式（避免HTTPS下Cookie被拦截）
CSRF_COOKIE_SAMESITE = 'None'  # HTTPS必须设为None，HTTP设为Lax
SESSION_COOKIE_SAMESITE = 'None'

# 4. 允许CSRF Cookie跨域（适配内网穿透）
CSRF_COOKIE_DOMAIN = None  # 本地开发设为None，生产环境填后端域名
SESSION_COOKIE_DOMAIN = None

# 5. 禁用CSRF的HTTP Referer验证（HTTPS下Referer可能丢失）
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'  # 保留默认失败视图
# settings.py 末尾（确保位置正确）
REST_FRAMEWORK = {
    # 确认配置无误（复制粘贴以下内容）
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    # 可选：关闭认证（彻底排除认证因素）
    'DEFAULT_AUTHENTICATION_CLASSES': [],
}