"""
Django settings for food_sort_system project.

Generated by 'django-admin startproject' using Django 4.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^0+j2%jr91kwx8sdviw1p++&@^ble7#r*-bhip^9*u!hpbmjv0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ========== 核心修改：替换为最新的cpolar域名 ==========
ALLOWED_HOSTS = [
    "4f75eb32.r10.cpolar.top",  # 后端新内网穿透域名（替换旧的1b30ab41）
    "1821c9ea.r10.cpolar.top",  # 前端新内网穿透域名（替换旧的49436143）
    "localhost",
    "127.0.0.1",
    "0.0.0.0",
]


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 已有的应用
    'category.apps.CategoryConfig',
    'orders.apps.OrdersConfig',
    'corsheaders',  # 跨域应用
    
    # 新增：注册 DRF
    'rest_framework',
]

MIDDLEWARE = [
    # 新增：跨域中间件（必须放在首位）
    'corsheaders.middleware.CorsMiddleware',
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # 恢复CSRF中间件（取消注释）
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'food_sort_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'food_sort_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'zh-hans'  # 中文
TIME_ZONE = 'Asia/Shanghai'  # 上海时区
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ========== 核心修改：替换为最新的cpolar域名 ==========
# 允许携带Cookie（CSRF Token核心）
CORS_ALLOW_CREDENTIALS = True

# 允许的跨域源（替换旧域名）
CORS_ALLOWED_ORIGINS = [
    "http://1821c9ea.r10.cpolar.top",   # 前端HTTP（新域名，替换旧的49436143）
    "https://1821c9ea.r10.cpolar.top",  # 前端HTTPS（新域名，替换旧的49436143）
    "http://4f75eb32.r10.cpolar.top",   # 后端HTTP（新域名，替换旧的1b30ab41）
    "https://4f75eb32.r10.cpolar.top",  # 后端HTTPS（新域名，替换旧的1b30ab41）
    "http://localhost:5174",
    "http://127.0.0.1:5174",
]

# 允许所有请求头（覆盖HTTPS环境的所有场景）
CORS_ALLOW_HEADERS = [
    "X-CSRFToken",
    "Content-Type",
    "Authorization",
    "Origin",
    "Referer",
    "X-Requested-With",
    "Accept",
    "Accept-Encoding",
    "User-Agent",
]

# 允许所有请求方法
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "OPTIONS",
    "PATCH",
]

# ========== 核心修改：替换为最新的cpolar域名 ==========
# 1. CSRF信任的源（替换旧域名）
CSRF_TRUSTED_ORIGINS = [
    "http://1821c9ea.r10.cpolar.top",   # 前端HTTP（新域名，替换旧的49436143）
    "https://1821c9ea.r10.cpolar.top",  # 前端HTTPS（新域名，替换旧的49436143）
    "http://4f75eb32.r10.cpolar.top",   # 后端HTTP（新域名，替换旧的1b30ab41）
    "https://4f75eb32.r10.cpolar.top",  # 后端HTTPS（新域名，替换旧的1b30ab41）
    "http://localhost:5174",
    "http://127.0.0.1:5174",
]

# 2. HTTPS环境下开启Cookie的Secure（关键！适配cpolar的HTTPS）
CSRF_COOKIE_SECURE = True   # HTTPS必须设为True
SESSION_COOKIE_SECURE = True  # 同步开启

# 3. SameSite设为Lax（None在部分浏览器会被拦截，Lax兼容性更好）
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

# 4. 取消自定义CSRF失败视图，用默认配置
# CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'

# ========== DRF配置（关闭权限验证，避免干扰） ==========
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [],
}